taxi_booking_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('trips.urls','trips'), namespace='trips')),
    path('users/', include(('users.urls','users'), namespace='users')),
   
]

trips/urls.py
from django.urls import path, include
from . import views

app_name = 'trips'
urlpatterns = [
    # Include default auth urls.
    path('', views.index, name ='index'),
    path('book/', views.book_trip, name ='book'),
    path('trips/', views.trips, name ='trips'),
    path('delete_trip/<int:id>/', views.delete_trip, name='delete-trip')

    
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page
    path('register/', views.register, name ='register'),
]

trips/models.py
from django.db import models
# from address.models import AddressField
from users.models import Driver
from django.contrib.auth.models import User

# Create your models here.

class Trip(models.Model):
    PAYMENT_METHODS = (
        ('1', 'Card'),
        ('2', 'Cash'),
    )
    customer = models.OneToOneField(User ,on_delete=models.CASCADE)
    pick_up_time = models.DateTimeField(blank=False, null=False)
    pick_up_place = models.CharField(max_length=80, blank=False, null=False)
    drop_off_place = models.CharField(max_length=80, blank=False, null=False)
    payment_method = models.CharField(max_length=1, choices=PAYMENT_METHODS)
    driver = models.OneToOneField(Driver , on_delete=models.CASCADE)

    def __str__(self):  
        return f"{self.pick_up_place} => {self.drop_off_place}"

trips/forms.py
from django import forms
from trips.models import Trip
import datetime
from django.forms import widgets
from django.contrib.admin import widgets  



class InputForm(forms.ModelForm): 
    PAYMENT_METHODS = (
            ('1', 'Card'),
            ('2', 'Cash'),
    )
    pick_up_time = forms.DateTimeField()
    pick_up_place = forms.CharField(max_length=100, label = 'Pick up place')
    payment_method  = forms.ChoiceField(widget=forms.RadioSelect,choices=PAYMENT_METHODS)
    drop_off_place = forms.CharField(max_length=80, label = 'Drop off place')
    
    class Meta:
        model = Trip
        fields = ('pick_up_place','drop_off_place','pick_up_time','payment_method','driver')

trips/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from trips.forms import InputForm
from django.contrib import messages
from trips.models import Trip

# Create your views here.
def index(request):
    return render(request, 'trips/index.html')



def book_trip(request):

    form = InputForm(request.POST)
    if request.method =='POST':
       
        if form.is_valid():
            event=form.save(commit=False)
            event.customer=request.user
            event.save()
            return redirect('trips:trips')    
        else:
            messages.error(request, "Error")
            
    return render(request, 'trips/book.html',{'form':form})
    
def trips(request):
    trips = Trip.objects.filter(customer=request.user)
    print(trips)
    context = {
        "trips_list": trips,
    }
    return render(request, 'trips/trips.html', context)

def delete_trip(request, id):
    delete = Trip.objects.get(id = id)
    delete.delete()
    
    return redirect ('trips:trips')

trips/templates/trips/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Taxi</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="">
        
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'trips:index' %}">Taxi Booking System</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'trips:trips' %}">Trips</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'trips:book' %}">Book a Trip</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:register' %}">Register</a>
            </li>
            {% endif %}
          </ul>
          <span class="navbar-text">
            {% if user.is_authenticated %}
            <p>You are logged in as {{user.username}}</p>
            {% endif %}
          </span>
        </div>
      </div>
    </nav>
      <main role="main" class="container">
        <div>
          {% block content %}{% endblock content %}
        </div>
      </main>
      <script src="" async defer></script>
  </body>
</html>

trips/templates/trips/book.html
{% extends 'trips/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div id="results">

  <div class="container-fluid">
      <form method="post" action="{% url 'trips:book' %}" class="form">
          {% csrf_token %}
          {{ form|crispy }} 
          <button name="submit" class="btn btn-primary">Submit</button>
          <input type="hidden" name="next" value="" />
          
      </form>
      
  </div>
</div>

        
{% endblock  %}

trips/templates/trips/index.html
{% extends 'trips/base.html' %}
{% block content %}
<div class="jumbotron">
    <h1 class="display-3">Track your Trips!</h1>
    <p>It is free and it always will be for free.</p>
</div>
{% endblock  %}

trips/templates/trips/trips.html
{% extends 'trips/base.html' %}
{% block content %}
<div class="jumbotron">
    <h1 class="display-3">Track your Trips!</h1>
    <p>It is free and it always will be for free.</p>
</div>
{% for trip in trips_list %}
   
    <div class="card w-50">
    <div class="card-body">
        <h5><center><b><span style="color:black;">Trip information: </b><center></h5>
        <p> <b><span style="color:black;">FROM:</b> {{trip.pick_up_place}}</p>
        <p> <b><span style="color:black;"> AT: </b>   {{trip.pick_up_time}}</p>
        <p> <b><span style="color:black;">GOING TO: </b>   {{trip.drop_off_place}}</p>
        <p> <b><span style="color:black;">Taxi Driver Information:</b> {{trip.driver.first_name}}, {{trip.driver.car_color}} {{trip.driver.car_model}}, {{trip.driver.car_license_plate}} </p>
        <a href="{% url 'trips:delete-trip' id=trip.id %}" class="btn btn-danger">Delete</a>
    </div>
    </div>
    
{% endfor %}
{% endblock  %}